cat log if error in TeX for issue #52

diff --git a/run b/run
--- a/run
+++ b/run
@@ -198,31 +198,31 @@ export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
 
 echo pdf
 
-pdflatex \\batchmode \\input omstd20.tex
-if (grep -i rerun omstd20.log)
+pdflatex \\batchmode \\input omstd20.tex ||(echo "ERROR in TeX"; cat omstd20.log; false)
+if (grep -i rerun omstd20.log;false)
   then
-  pdflatex \\batchmode \\input omstd20.tex
+  pdflatex \\batchmode \\input omstd20.tex ||(echo "ERROR in TeX"; cat omstd20.log;false)
   if (grep -i rerun omstd20.log)
     then 
-    pdflatex \\batchmode \\input omstd20.tex
+    pdflatex \\batchmode \\input omstd20.tex ||(echo "ERROR in TeX"; cat omstd20.log;false)
     if (grep -i rerun omstd20.log)
       then
-      pdflatex \\batchmode \\input omstd20.tex
+      pdflatex \\batchmode \\input omstd20.tex ||(echo "ERROR in TeX"; cat omstd20.log;false)
     fi
   fi
 fi
 
 echo pdf-diff
-pdflatex \\batchmode \\input omstd20-diff.tex
+pdflatex \\batchmode \\input omstd20-diff.tex ||(echo "ERROR in TeX"; cat omstd20-diff.log;false)
 if (grep -i rerun omstd20-diff.log)
   then
-  pdflatex \\batchmode \\input omstd20-diff.tex
+  pdflatex \\batchmode \\input omstd20-diff.tex ||(echo "ERROR in TeX"; cat omstd20-diff.log;false)
   if (grep -i rerun omstd20-diff.log)
     then 
-    pdflatex \\batchmode \\input omstd20-diff.tex
+    pdflatex \\batchmode \\input omstd20-diff.tex ||(echo "ERROR in TeX"; cat omstd20-diff.log;false)
     if (grep -i rerun omstd20-diff.log)
       then
-      pdflatex \\batchmode \\input omstd20-diff.tex
+      pdflatex \\batchmode \\input omstd20-diff.tex ||(echo "ERROR in TeX"; cat omstd20-diff.log;false)
     fi
   fi
 fi
